- hosts: localhost
  connection: local

  tasks:

    - name: Install Role MySQL
      local_action: command ansible-galaxy install -f geerlingguy.mysql

    - name: Installing MYSQL
      include_role:
          name: geerlingguy.mysql
